apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: docker-build-mq-tls-build
  namespace: mq
  labels:
    name: docker-build-mq-tls-build
spec:
  triggers:
    - type: GitHub
      github:
        secret: secret101
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange
  source:
    type: Git
    git:
      uri: 'https://github.com/DAVEXACOM/ibm-mqadvanced-server-tls-build.git'
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: 'ibm-mqadvanced-server-integration:9.1.3.0-r4-amd64'
        namespace: mq
      env:
        - name: EXAMPLE
          value: sample-app
  output:
    to:
      kind: ImageStreamTag
      name: 'ibm-mqadvanced-server-tls:9.1.3.0-r4-amd64-build'
  postCommit:
    args:
      - bundle
      - exec
      - rake
      - test
