kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewBuild
  selfLink: >-
    /apis/build.openshift.io/v1/namespaces/da-mq/buildconfigs/ibm-mqadvanced-server-tls-build
  resourceVersion: '12429287'
  name: ibm-mqadvanced-server-tls-build
  uid: d2ceb29a-d5a0-4809-82d0-41b76045e670
  creationTimestamp: '2021-01-08T06:01:29Z'
  managedFields:
    - manager: oc
      operation: Update
      apiVersion: build.openshift.io/v1
      time: '2021-01-08T06:01:29Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:openshift.io/generated-by': {}
          'f:labels':
            .: {}
            'f:build': {}
        'f:spec':
          'f:output':
            'f:to':
              .: {}
              'f:kind': {}
              'f:name': {}
          'f:runPolicy': {}
          'f:source':
            'f:git':
              .: {}
              'f:uri': {}
            'f:type': {}
          'f:strategy':
            'f:dockerStrategy':
              .: {}
              'f:from':
                .: {}
                'f:kind': {}
                'f:name': {}
                'f:namespace': {}
            'f:type': {}
    - manager: openshift-apiserver
      operation: Update
      apiVersion: build.openshift.io/v1
      time: '2021-01-19T22:20:17Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:triggers': {}
        'f:status':
          'f:lastVersion': {}
  namespace: da-mq
  labels:
    build: ibm-mqadvanced-server-tls-build
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'ibm-mqadvanced-server-tls-build:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: ImageStreamTag
        namespace: da-mq
        name: 'ibm-mqadvanced-server-integration:9.1.3.0-r4-amd64'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/DAVEXACOM/ibm-mqadvanced-server-tls-build.git'
  triggers:
    - type: GitHub
      github:
        secret: We6CNZtQYltIGtLeClRG
    - type: Generic
      generic:
        secret: 7RQYdsCcD9aENybliErK
    - type: ConfigChange
    - type: ImageChange
      imageChange:
        lastTriggeredImageID: >-
          davexacom/ibm-mqadvanced-server-integration@sha256:0cd8142e68ae76a84b06540fd93caf9f964045dbd35c6d0c7efb309e29f2bbb0
  runPolicy: Serial
status:
  lastVersion: 2
