kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    openshift.io/image.dockerRepositoryCheck: '2021-01-13T23:23:02Z'
  selfLink: >-
    /apis/image.openshift.io/v1/namespaces/da-mq/imagestreams/ibm-mqadvanced-server-integration
  resourceVersion: '5990520'
  name: ibm-mqadvanced-server-integration
  uid: f07e9035-3005-44c7-bba4-4a3d79977f5c
  creationTimestamp: '2021-01-08T06:00:33Z'
  generation: 4
  managedFields:
    - manager: kubectl-create
      operation: Update
      apiVersion: image.openshift.io/v1
      time: '2021-01-08T06:00:33Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:tags':
            .: {}
            'k:{"name":"9.1.3.0-r4-amd64"}':
              .: {}
              'f:annotations': {}
              'f:from':
                .: {}
                'f:kind': {}
                'f:name': {}
              'f:generation': {}
              'f:importPolicy': {}
              'f:name': {}
              'f:referencePolicy':
                .: {}
                'f:type': {}
  namespace: da-mq
spec:
  lookupPolicy:
    local: false
  tags:
    - name: 9.1.3.0-r4-amd64
      annotations: null
      from:
        kind: DockerImage
        name: 'davexacom/ibm-mqadvanced-server-integration:9.1.3.0-r4-amd64'
      generation: 2
      importPolicy: {}
      referencePolicy:
        type: Source
    - name: 9.2.0.1-r1-eus
      annotations: null
      from:
        kind: DockerImage
        name: 'cp.icr.io/cp/ibm-mqadvanced-server-integration:9.2.0.1-r1-eus'
      generation: 4
      importPolicy: {}
      referencePolicy:
        type: Source
status:
  dockerImageRepository: >-
    image-registry.openshift-image-registry.svc:5000/da-mq/ibm-mqadvanced-server-integration
  publicDockerImageRepository: >-
    default-route-openshift-image-registry.apps-crc.testing/da-mq/ibm-mqadvanced-server-integration
  tags:
    - tag: 9.1.3.0-r4-amd64
      items:
        - created: '2021-01-08T06:00:40Z'
          dockerImageReference: >-
            davexacom/ibm-mqadvanced-server-integration@sha256:0cd8142e68ae76a84b06540fd93caf9f964045dbd35c6d0c7efb309e29f2bbb0
          image: >-
            sha256:0cd8142e68ae76a84b06540fd93caf9f964045dbd35c6d0c7efb309e29f2bbb0
          generation: 2
    - tag: 9.2.0.1-r1-eus
      items:
        - created: '2021-01-13T23:23:02Z'
          dockerImageReference: >-
            cp.icr.io/cp/ibm-mqadvanced-server-integration@sha256:41a51066afb4d4909cf0a4ccb96e29a327951472d4a1b1709bf76be6a13c9185
          image: >-
            sha256:41a51066afb4d4909cf0a4ccb96e29a327951472d4a1b1709bf76be6a13c9185
          generation: 4
